export enum GeoLocationAnalyticsType {
    FORM, LANDING_PAGE, LANDING_PAGE_FORM,CAMPAIGN_FORM, CAMPAIGN_LANDING_PAGE, 
    CAMPAIGN_LANDING_PAGE_FORM,OTHER_LINKS,PARTNER_LANDING_PAGE,PARTNER_LANDING_PAGE_FORM,
    DAM, FORM_SUBMIT    
}
