import {Category} from '../models/category';
export class SaveVideoFile {
    id: number;
    uploadedUserId: number;
    title: string;
    categoryId: number;
    category: Category;
    categoryName : string;
    categories: Category[];
    viewBy: string;
    tags: string[];
    customerId: number;
    imagePath: string;
    imageFile: any;
    gifImagePath: string;
    description: string;
    playerColor: string;
    enableVideoController: boolean;
    controllerColor: string="";
    allowSharing: boolean;
    enableSettings: boolean;
    allowFullscreen: boolean;
    allowComments: boolean;
    allowLikes: boolean;
    enableCasting: boolean;
    allowEmbed: boolean;
    transparency: number=0;
    action: string;
    callACtion: boolean;
    name: boolean;
    skip: boolean;
    upperText: string;
    lowerText: string;
    startOfVideo: boolean;
    endOfVideo: boolean;
    imageFiles: string[];
    error: string;
    gifFiles: string[];
    videoLength: number;
    bitRate: number;
    videoPath: string;
    uploadedDate: Date;
    uploadedBy: string;
    alias: string;
    is360video: boolean;
    defaultSetting: boolean;
    views: number;
    watchedFully: number;
    brandingLogoUri: string;
    brandingLogoDescUri: string;
    companyName: string;
    enableVideoCobrandingLogo:boolean;
    uploadedUserName:string = "";
    processed:boolean;
    access:boolean;
    damId : number;
    tagNames : string[];
    toolTipTagNames: string = "";
    folderId:number = 0;
    shareAsWhiteLabeledAsset = false;
    disableWhiteLabelOption = false;
    whiteLabeledToolTipMessage = "";
    partnerGroupIds = []
    partnerIds = []
    partnerGroupSelected = false;
    partnershipIds = [];
    isPublishedToPartnerGroups = false;
 }
