import {Category} from '../models/category';
import { FileDropDirective, FileItem } from 'ng2-file-upload';
export class SaveVideoFile {
    id: number;
    title: string;
    categoryId: number;
    categories: Category[];
    viewBy: string;
    tags: string[];
    customerId: number;
    imagePath: string;
    imageFile: any;
    gifImagePath: string;
    description: string;
    playerColor: string;
    enableVideoController: boolean;
    controllerColor: string;
    allowSharing: boolean;
    enableSettings: boolean;
    allowFullscreen: boolean;
    allowComments: boolean;
    allowLikes: boolean;
    enableCasting: boolean;
    allowEmbed: boolean;
    transparency: number;
    action: string;
    callACtion: boolean;
    name: boolean;
    skip: boolean;
    upperText: string;
    lowerText: string;
    startOfVideo: boolean;
    endOfVideo: boolean;
    imageFiles: string[];
    error: string;
    gifFiles: string[];
    videoLength: number;
    bitRate: number;
    videoPath: string;
    uploadedDate: Date;
    uploadedBy: string;
    alias: string;
    is360video: boolean;
 }