export enum AddContactsOption {
    ADDCONTACT,
    COPYFROMCLIPBOARD,
    CSVUPLOAD,
    SALESFORCECONTACTS,
    GOOGLECONTACTS,
    ZOHOCONTACTS,
    MARKETOCONTACTS,
    MICROSOFTCONTACTS
}